# Netlify Configuration
[build]
  publish = "."
  command = "echo 'No build needed'"

# Redirect API calls to backend (if you deploy backend separately)
[[redirects]]
  from = "/api/*"
  to = "https://YOUR-BACKEND-URL.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback (for client-side routing if needed)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
